<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="343433" started-at="2017-08-10T06:45:31Z" finished-at="2017-08-10T06:51:14Z">
    <groups>
    </groups>
    <test name="Nopackage" duration-ms="343433" started-at="2017-08-10T06:45:31Z" finished-at="2017-08-10T06:51:14Z">
      <class name="Test.Register">
        <test-method status="FAIL" signature="checkvalidRegistration()[pri:1, instance:Test.Register@7d9d1a19]" name="checkvalidRegistration" duration-ms="40044" started-at="2017-08-10T12:15:31Z" finished-at="2017-08-10T12:16:11Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<[Please enter email address].> but was:<[An Account activation link has been sent to %@. Please check your Spam folder too].>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<[Please enter email address].> but was:<[An Account activation link has been sent to %@. Please check your Spam folder too].>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at Test.Register.checkvalidRegistration(Register.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkvalidRegistration -->
        <test-method status="FAIL" signature="nickNamevalidation()[pri:2, instance:Test.Register@7d9d1a19]" name="nickNamevalidation" duration-ms="84023" started-at="2017-08-10T12:16:11Z" finished-at="2017-08-10T12:17:35Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...lease enter Nickname[]> but was:<...lease enter Nickname[.]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...lease enter Nickname[]> but was:<...lease enter Nickname[.]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at Test.Register.nickNamevalidation(Register.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nickNamevalidation -->
        <test-method status="FAIL" signature="verifyExistingNickNamevalidation()[pri:3, instance:Test.Register@7d9d1a19]" name="verifyExistingNickNamevalidation" duration-ms="34914" started-at="2017-08-10T12:17:35Z" finished-at="2017-08-10T12:18:10Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<[nickname already exist. Please try with different Nickname.]> but was:<[This email address already exists]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<[nickname already exist. Please try with different Nickname.]> but was:<[This email address already exists]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at Test.Register.verifyExistingNickNamevalidation(Register.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistingNickNamevalidation -->
        <test-method status="FAIL" signature="verifyExistingEmailIDValidation()[pri:4, instance:Test.Register@7d9d1a19]" name="verifyExistingEmailIDValidation" duration-ms="65957" started-at="2017-08-10T12:18:10Z" finished-at="2017-08-10T12:19:16Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...dress already exists[.]> but was:<...dress already exists[]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...dress already exists[.]> but was:<...dress already exists[]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at Test.Register.verifyExistingEmailIDValidation(Register.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistingEmailIDValidation -->
        <test-method status="PASS" signature="verifyEmptyEmailIdFiels()[pri:5, instance:Test.Register@7d9d1a19]" name="verifyEmptyEmailIdFiels" duration-ms="27230" started-at="2017-08-10T12:19:16Z" finished-at="2017-08-10T12:19:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmptyEmailIdFiels -->
        <test-method status="PASS" signature="invalidEmailIdvalidationError()[pri:6, instance:Test.Register@7d9d1a19]" name="invalidEmailIdvalidationError" duration-ms="24332" started-at="2017-08-10T12:19:43Z" finished-at="2017-08-10T12:20:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmailIdvalidationError -->
        <test-method status="PASS" signature="genderValidation()[pri:7, instance:Test.Register@7d9d1a19]" name="genderValidation" duration-ms="44195" started-at="2017-08-10T12:20:07Z" finished-at="2017-08-10T12:20:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- genderValidation -->
        <test-method status="PASS" signature="agevalidationError()[pri:8, instance:Test.Register@7d9d1a19]" name="agevalidationError" duration-ms="12528" started-at="2017-08-10T12:20:52Z" finished-at="2017-08-10T12:21:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- agevalidationError -->
        <test-method status="PASS" signature="passwordError()[pri:9, instance:Test.Register@7d9d1a19]" name="passwordError" duration-ms="10153" started-at="2017-08-10T12:21:04Z" finished-at="2017-08-10T12:21:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passwordError -->
      </class> <!-- Test.Register -->
      <class name="BasePackage.DriverClass">
        <test-method status="PASS" signature="launnApplication()[pri:0, instance:BasePackage.DriverClass@4883b407]" name="launnApplication" is-config="true" duration-ms="21303" started-at="2017-08-10T12:15:10Z" finished-at="2017-08-10T12:15:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launnApplication -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:BasePackage.DriverClass@4883b407]" name="closeApplication" is-config="true" duration-ms="1235" started-at="2017-08-10T12:21:14Z" finished-at="2017-08-10T12:21:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- BasePackage.DriverClass -->
    </test> <!-- Nopackage -->
  </suite> <!-- Suite1 -->
</testng-results>
